global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bolt'
    static_configs:
      - targets: ['192.168.0.194:9091']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 3s
